---
- name: Set facts
  include_tasks: set_facts.yml

- name: Run prereqs
  include_tasks: prereqs.yml

- name: Run setup
  include_tasks: setup.yml

- name: Install gosu
  include_tasks: gosu.yml

- name: Install prometheus
  include_tasks: prometheus.yml
  when: is_prometheus

- name: Install alertmanager
  include_tasks: alertmanager.yml
  when: is_alertmanager

- name: Install pushgateway
  include_tasks: pushgateway.yml
  when: is_pushgateway

- name: Install node_exporter
  include_tasks: node_exporter.yml
  when: is_node_exporter

- name: Install blackbox_exporter
  include_tasks: blackbox_exporter.yml
  when: is_blackbox_exporter

- name: Install solr_exporter
  include_tasks: solr_exporter.yml
  when: is_solr_exporter

- name: Setup configs
  include_tasks: config.yml
  when: enable_config

- name: Setup services
  include_tasks: service.yml
