---
- name: Check prometheus version
  command: "{{ prometheus_bin_path }}/prometheus --version"
  args:
    chdir: "{{ prometheus_bin_path }}"
  register: prometheus_check
  ignore_errors: yes
  changed_when: no

- name: Download prometheus package
  get_url:
    url: "{{ prometheus_url }}"
    dest: "{{ prometheus_releases_path }}"
    validate_certs: "{{ prometheus_ssl_verify }}"
  when: prometheus_check is failed or ( prometheus_version not in prometheus_check.stderr ) or prometheus_force_deploy

- name: Unarchive prometheus package
  unarchive:
    copy: no
    src: "{{ prometheus_releases_path }}/{{ prometheus_package }}"
    dest: /tmp
  when: prometheus_check is failed or ( prometheus_version not in prometheus_check.stderr ) or prometheus_force_deploy

- name: Copy prometheus binary
  copy:
    src: "/tmp/{{ prometheus_release_name }}/{{ item }}"
    dest: "{{ prometheus_bin_path }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    remote_src: yes
    mode: 0755
  with_items:
    - prometheus
    - promtool
  notify: restart prometheus
  when: prometheus_check is failed or ( prometheus_version not in prometheus_check.stderr ) or prometheus_force_deploy

- name: Link prometheus binary
  file:
    src: "{{ prometheus_bin_path }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  with_items:
    - prometheus
    - promtool
