---
- name: Create prometheus sysv init script (Ubuntu 14.04)
  template:
    src: prometheus.init.j2
    dest: /etc/init.d/prometheus
    owner: root
    group: root
    mode: 0755
  when: is_prometheus and (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: Create prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0755
  when: is_prometheus and ((ansible_os_family  == "RedHat" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8"))

- name: Enable prometheus service
  service:
    name: prometheus
    enabled: yes
    state: started
  when: is_prometheus

- name: Create alertmanager sysv init script (Ubuntu 14.04)
  template:
    src: alertmanager.init.j2
    dest: /etc/init.d/alertmanager
    owner: root
    group: root
    mode: 0755
  when: is_alertmanager and (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: Create alertmanager systemd service
  template:
    src: alertmanager.service.j2
    dest: /lib/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0755
  when: is_alertmanager and ((ansible_os_family  == "RedHat" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8"))

- name: Enable alertmanager service
  service:
    name: alertmanager
    enabled: yes
    state: started
  when: is_alertmanager