---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: "POST"

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: restart pushgateway
  service:
    name: pushgateway
    state: restarted

- name: restart node exporter
  service:
    name: node_exporter
    state: restarted