---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  uri:
    url: "http://localhost:{{ prometheus_port }}/-/reload"
    method: "POST"

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  uri:
    url: "http://localhost:{{ alertmanager_port }}/-/reload"
    method: "POST"

- name: restart pushgateway
  service:
    name: pushgateway
    state: restarted

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted

- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: reload blackbox_exporter
  uri:
    url: "http://localhost:{{ blackbox_exporter_port }}/-/reload"
    method: "POST"

- name: restart solr_exporter
  service:
    name: solr_exporter
    state: restarted